# Multi-Stage pipeline which builds a Docker image, scan it with Snyk, have Snyk report reviewed by security team before pushing image to ACR 

name: $(BuildDefinitionName)_$(date:yyyMMdd)$(rev:.r)

trigger: none
# - master

resources:
- repo: self

pr: none

# Linux OS self-hosted Agent Pool
pool: 
  name: Selfhosted-PRC382-AKS
  demands:
  - agent.os -equals Linux 

variables:
- group: PRC382-Variables


# Build Stage
stages: 
- stage: Build
  displayName: Build and scan Linux image 
  jobs:
  - job: Build
    displayName: Build and scan Linux image
    steps:
    

    # Move created image to the Staging Directory 
    - task: CmdLine@2
      inputs:
        script: |
          docker pull $(imageRepository2):$(latestTag)
          docker image save $(imageRepository2):$(latestTag) -o $(Build.ArtifactStagingDirectory)/$(imageRepository2)